openedx/tutor-contrib-aspects

tutoroars/plugin.py
tutoroars/templates/oars/apps/data/assets/charts/xAPI_events_1.yaml
tutoroars/templates/oars/apps/data/assets/charts/xAPI_events_by_course_3.yaml
tutoroars/templates/oars/apps/data/assets/charts/xAPI_problem_events_by_block_2.yaml
tutoroars/templates/oars/apps/data/assets/dashboards/xAPI_events_1.yaml
tutoroars/templates/oars/apps/data/assets/databases/OpenedX_Clickhouse.yaml
tutoroars/templates/oars/apps/data/assets/databases/OpenedX_MySQL.yaml
tutoroars/templates/oars/apps/data/assets/datasets/OpenedX_Clickhouse/xapi_events_all_parsed.yaml
tutoroars/templates/oars/apps/data/assets/metadata.yaml
tutoroars/templates/oars/apps/pythonpath/requirements.txt
tutoroars/templates/oars/apps/pythonpath/superset-dashboard.py
tutoroars/templates/oars/jobs/init/clickhouse-demo-xapi-data.sh
tutoroars/templates/oars/jobs/init/superset-add-admin.sh
tutoroars/templates/oars/jobs/init/superset-api-dashboard.sh
tutoroars/templates/oars/jobs/init/superset-init-security.sh

Finalizes Clickhouse + MySQL + Superset integration for https://github.com/openedx/openedx-oars/issues/30:
* Sets up an admin user to access the REST API
* Imports the exported Superset assets using `superset-api-client`, including database passwords for Clickhouse and MySQL.
* Publishes the imported dashboard and charts so any logged-in user with course access can see it.
* Adds the Row-Level Security Filters for the Clickhouse dataset during initialization.
**Dependencies**
* https://github.com/openedx/tutor-contrib-clickhouse/pull/4
* https://github.com/openedx/tutor-contrib-superset/pull/6
**Author Notes**
1. UUIDs for the Superset assets are all hard-coded in the `data/assets` dir. Should we make these configurable, in case they happen to clash with existing UUIDs?
**Testing …

Creates OARS datasets, charts, and dashboards in Superset

---

README.rst

This PR updates the README file adding more info about the plugin.

docs: improve project readme format

---

tutoroars/patches/local-docker-compose-dev-jobs-services
tutoroars/patches/local-docker-compose-jobs-services
tutoroars/plugin.py
tutoroars/templates/oars/apps/data/superset/databases/OpenedX_Clickhouse.yaml
tutoroars/templates/oars/apps/pythonpath/superset-dashboard.py
tutoroars/templates/oars/apps/scripts/clickhouse-demo-xapi-data.sh
tutoroars/templates/oars/jobs/init/configure-oars-lms.sh
tutoroars/templates/oars/jobs/init/oars_init_schemas_tables_users.sh

This PR adds support for clickhouse cloud
Depends on: 
- https://github.com/openedx/tutor-contrib-clickhouse/pull/16
- https://github.com/openedx/tutor-contrib-ralph/pull/20
- https://github.com/openedx/tutor-contrib-superset/pull/32

feat: add support for clickhouse cloud

---

tutoroars/patches/k8s-jobs
tutoroars/patches/local-docker-compose-jobs-services
tutoroars/plugin.py

Create a config to be able to modify the oars docker image.
Upgrade python to 3.8.16

chore: upgrade python to latest version

---

tutoroars/templates/oars/jobs/init/oars_init_schemas_tables_users.sh

- Extract org and object id into the top level of xapi_events_all_parsed.
- Use the String type instead of JSON for the event JSON data, since the JSON type is so poorly supported.
- Add time_last_dumped to event_sink.relationships PK to help speed up queries on that data

refactor: Update xapi_events_all_parsed and supporting view

---

tutoroars/templates/oars/jobs/init/oars_init_schemas_tables_users.sh

This PR allows to change the `XAPI_AGENT_IFI_TYPE` setting without breaking the `actor_id` column
- Fixes #48

feat: add support for different actor_id sources

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/scripts/aspects/dbt.sh
tutoraspects/templates/aspects/apps/scripts/aspects/profiles.yml
tutoraspects/templates/aspects/jobs/init/dbt/init-dbt.sh

Last project renaming PR, we've moved oars-dbt to aspects-dbt and need to update references here.

refactor: Update oars-dbt repo to aspects-dbt

---

tutoraspects/plugin.py

Tried it locally without issue

chore: Upgrade Ralph to 3.8.0

---

setup.cfg

Fixes the current version so the release workflow can work

build: correct current version for release

---

.github/workflows/release.yaml

build: fix release workflow

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_jinja_filters.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py

This PR allows to create and use custom jinja templates

feat: add support for extra jinja filters

---

tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
tutoraspects/templates/aspects/jobs/init/superset/init-superset.sh

This PR allows importing the roles associated with the dashboard:
TODO:
- Add documentation

feat: allow to import dashboards roles

---

.gitignore
tutoraspects/commands_v0.py
tutoraspects/commands_v1.py
tutoraspects/plugin.py
tutoraspects/templates/aspects/build/aspects-superset/Dockerfile

This PR adds compatibility with tutor14 and tutor15
Fixes: #95

feat: backward compatibility with tutor14

---

.ci/config.yml
.github/workflows/test-tutor-aspects.yml
tutoraspects/plugin.py
tutoraspects/templates/aspects/build/aspects/Dockerfile

This PR creates a test workflow that make sure a tutor local environment can be run. It only runs on pushes to the main branch and when someone comments `test tutor aspects local` or `test tutor aspects dev` in a PR
Fixes: #74

test: add tests for tutor local env

---

.github/workflows/test-tutor-aspects.yml

This PR fixes the CI workflow for tests

test: correct tutor test workflow

---

.github/workflows/build-aspects.yaml
.github/workflows/test-tutor-aspects.yml

This PR adds a CI workflow to build docker images

build: add ci workflow to build and push docker images

---

README.rst
tutoraspects/patches/superset-row-level-security
tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py
tutoraspects/templates/aspects/apps/superset/security/roles.json
tutoraspects/templates/openedx-assets/Actor_IDs_over_time_47.yaml
tutoraspects/templates/openedx-assets/Courses_44.yaml
tutoraspects/templates/openedx-assets/Event_type_45.yaml
tutoraspects/templates/openedx-assets/Events_per_course_46.yaml
tutoraspects/templates/openedx-assets/Instructor_dashboard_9.yaml
tutoraspects/templates/openedx-assets/Last_course_syncronized_41.yaml
tutoraspects/templates/openedx-assets/Last_received_xAPI_events_40.yaml
tutoraspects/templates/openedx-assets/Open_edX_Admin_Dashboard_2.yaml
tutoraspects/templates/openedx-assets/Operator_Dashboard_5.yaml
tutoraspects/templates/openedx-assets/Organizations_42.yaml
tutoraspects/templates/openedx-assets/Synchronized_Courses_39.yaml
tutoraspects/templates/openedx-assets/Unique_actors_43.yaml
tutoraspects/templates/openedx-assets/xAPI_events_38.yaml

This PR:
- Publish dashboards at import time
- Create a new dashboard and role for site operators.
- Deny access to non-instructors.
Fixes: 
- #145
- #151
Screenshots:
- Access denied for students
- Operator Dashboard

feat: add operator dashboard

---

.github/workflows/build-aspects.yaml

This PR corrects an error with the build workflow

build: build docker images on release created

---

.github/workflows/bump-version.yaml

This PR sets the correct name for the **bump-version** workflow

build: change default title for release PR

---

README.rst
tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
tutoraspects/templates/aspects/apps/superset/security/roles.json

This PR allows importing extra superset roles
Fixes #166

feat: import superset extra roles

---

tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
tutoraspects/templates/aspects/apps/superset/security/roles.json

Fixes #144 
This PR fixes an issue that was blocking instructors and students from accessing the superset instance.
This PR removes the permissions that don't belong to the Instructor role.

fix: block only students

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0009_course_dictionaries.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0010_course_dictionaries.py

Also creates dictionary backed tables for ease of use in joins. This change was suggested by ClickHouse support to greatly help our performance in basically all report queries.

feat: Add course and block names to in memory dictionaries

---

tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py

Reverts openedx/tutor-contrib-aspects#203 (needs to be squashed)

Revert "Fg/fix o auth token refresh"

---

tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py

fix: oauth token refresh solution -- squash commits

---

.github/workflows/bump-version.yaml

This PR partially fixes https://github.com/openedx/tutor-contrib-aspects/issues/227

chore: delete remote branch before release

---

LICENSE

The project has always stated in the readme that it's AGPL 3. This just adds the license file to the repo.
Closes #230

chore: Add license file

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0010_course_dictionaries.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0011_vector_replacingmergetree_xapi_raw.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0012_vector_replacingmergetree_xapi_parsed.py
tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh
tutoraspects/templates/aspects/jobs/init/aspects/init-aspects.sh
tutoraspects/templates/openedx-assets/assets/datasets/course_overviews.yaml

This fixes some issues I ran into with load testing in CH Cloud. One thing I haven't tested is how this all works on tutor local / dev so I'm putting in a PR for automation to check it. :)

fix: Changes needed to run in CH Cloud

---

tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh

This PR fixes an error in which the `dbt-packages` and `dbt-project` patches were not correctly injected

fix: print packages and project dbt correctly

---

tutoraspects/plugin.py

This PR upgrades dbt-aspects to `v2.2`

feat: upgrade dbt-aspects to v2.2

---

tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config.py
tutoraspects/templates/aspects/build/aspects-superset/Dockerfile
tutoraspects/templates/aspects/build/aspects-superset/requirements.txt

This PR enables alerts and reports
Fixes: #310

feat: enable alerts and reports

---

tutoraspects/plugin.py

Running this through CI to check for any glaring issues, will change to draft after we have an idea of whether this breaks anything.

feat: Upgrade ClickHouse to 23.8 LTS

---

.github/workflows/test-tutor-aspects.yml
tutoraspects/plugin.py

This PR upgrades `openedx-event-sink-clickhouse` to `0.2.2`

fix: update openedx-event-sink-clickhouse to 0.2.2

---

.github/workflows/test-tutor-aspects.yml

This PR adds tests in CI for custom commands in CI

test: add test for custom commands in CI

---

tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
tutoraspects/templates/aspects/apps/superset/pythonpath/create_row_level_security.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py
tutoraspects/templates/aspects/build/aspects-superset/Dockerfile
tutoraspects/templates/aspects/jobs/init/superset/init-superset.sh

Fixes: #381 
Known bugs:
- ~Assets imports~
- ~RLSF imports~
- ~SSO login/logout~

feat: upgrade superset to 3.0.0

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/jobs/init/init-lms.sh

This PR creates a FLAG to enable PII

fix: implement an enable PII flag

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0022_new_course_id_loc.py

- Update xapi_events_all_parsed to parse the course id from new places due to changes in how multi-question problem_checks are handled.

feat: Upgrade event-routing-backends to v7.0.0

---

tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py

This PR enables embedded Superset and charts feature flags.
This prepares the terrain for Instructor dashboard integration via Superset iframes.
https://medium.com/@khushbu.adav/embedding-superset-dashboards-in-your-react-application-7f282e3dbd88

feat: enable embedded superset and charts

---

scripts/utils.py

It caused this job to fail: https://github.com/openedx/tutor-contrib-aspects/actions/runs/6475334732/job/17582146376

fix: Incorrect path for assets introduced in the loc refactor

---

tutoraspects/templates/aspects/jobs/init/init-mysql.sh

fix: Make the Superset MySQL database utf8mb4

---

README.rst

docs: Fix duplicate https in doc links

---

tutoraspects/templates/aspects/build/aspects-superset/Dockerfile

Mostly bug fixing, but does have a nice improvement to filter loading times. Does not fix our filter bug, unfortunately.

feat: Upgrade Superset to 3.0.1

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0031_add_email_user_profile.py
tutoraspects/templates/aspects/build/aspects/requirements.txt

Adds email to the user_profile table.
Requires https://github.com/openedx/tutor-contrib-aspects/pull/582 to merge, and the temp commit on this branch to be updated to the new version before this can be merged.

feat: Upgrade event-sink-clickhouse to 1.0.0

---

tutoraspects/plugin.py

Should include the fix for MVs having their schema changed on recreate.

fix: Bump aspects-dbt to 3.4.1

---

tutoraspects/templates/aspects/build/aspects/requirements.txt

Fixes issues with dbt creating things in the wrong place.

fix: Upgrade dbt-clickhouse to 1.7.2

---

tutoraspects/plugin.py

This is working fine for me locally. I don't think there are any huge changes here, just trying to keep up to date.

feat: Upgrade Ralph to version 4.1.0

---

tutoraspects/plugin.py

Upgrade tools to support CCX courses

feat: upgrade requirements to support CCX courses

---

tutoraspects/patches/local-docker-compose-dev-services
tutoraspects/templates/aspects/apps/clickhouse/dev_config/server_config.xml

This PR sets the clickhouse log level to console.

fix: enable clickhouse console logging

---

.github/workflows/build-image.yaml

This PR fixes the build-image workflow

build: build images on bot PRs

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/ab_user.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/course_blocks.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/course_names.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/course_overviews.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/dashboards.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/dim_course_problems.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/dim_course_videos.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_course_grades.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_enrollments.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_enrollments_by_day.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_forum_interactions.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_learner_problem_course_summary.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_learner_problem_summary.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_pageview_engagement.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_problem_grades.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_problem_responses.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_transcript_usage.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_video_engagement.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_video_plays.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_watched_video_segments.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/hints_per_success.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/indexed_events.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/posts_per_user.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/query_log.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/slices.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/slowest_clickhouse_queries.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/superset_action_log.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/user_pii.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/xapi_events_all_parsed.yaml
tutoraspects/templates/openedx-assets/queries/indexed_events.sql

This PR corrects the schema of all datasets to use the available settings

fix: set correct schema for all datasets

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Individual_Learner_Reports.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Instructor_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Learner_Groups_Reports.yaml

This PR setups the dashboard `color_schema` to `supersetColors`

fix: set dashboard color_schema to supersetColors

---

.github/workflows/integration-test.yml
tutoraspects/commands_v1.py
tutoraspects/templates/aspects/apps/superset/pythonpath/performance_metrics.py
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Distribution_of_Current_Course_Grade.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Learners_with_Passing_Grade.yaml

I expect CI on this will fail until #750 is merged and I can rebase. I just want to make sure this fails SQL errors in the future.

fix: Fail Tutor command on performance_metrics failure

---

tutoraspects/patches/openedx-dev-dockerfile-post-python-requirements
tutoraspects/patches/openedx-dockerfile-post-python-requirements
tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py

This fixes mismatches between this plugin and the assets ids generated in the LMS plugin that cause translated dashboards to not embed properly. There is a matching PR in platform-plugin-aspects that is needed to complete this fix.

fix: Normalize localized asset UUIDs

---

tutoraspects/plugin.py

Adds support for new block ordering and enrollment timestamp to at risk learners model.

Upgrade aspects-dbt to 3.22

---

setup.py

fix: Use base.in for install_requires

---

tutoraspects/patches/openedx-dev-dockerfile-post-python-requirements
tutoraspects/patches/openedx-dockerfile-post-python-requirements

This contains the fix to remove superset guest token caching.

chore: Bump platform-plugin-aspect to 0.9.2

---

tutoraspects/templates/aspects/build/aspects-superset/localization/locale.yaml
tutoraspects/translations/translate_utils.py

Some languages don't have the "None" key that we're trying to get rid of. Error is here:
https://github.com/openedx/tutor-contrib-aspects/actions/runs/9055139927/job/24875808694

fix: Fix KeyError in compile_translations

---

tutoraspects/templates/aspects/build/aspects/Dockerfile

This PR improves the time it takes to run DBT by pre-installing required packages by `aspects-dbt`.

feat(perf): improve time of running dbt by pre installing requirements

---

tutoraspects/plugin.py

This PR upgrades aspects-dbt to 3.28.1 which improves performance on the `fact_navigation_completion`  dataset

chore: upgrade aspects-dbt to v3.28.1

---

tutoraspects/patches/openedx-dev-dockerfile-post-python-requirements
tutoraspects/patches/openedx-dockerfile-post-python-requirements

Fixes issues with course block ordering as well as section/subsection ordering.

fix: Bump platform-plugin-aspects to 0.9.7

---

tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py

It was supposed that the connection string from ClickHouse and MySQL were fixed by this PR: https://github.com/openedx/tutor-contrib-aspects/pull/581. However, the asset generated with a random user/password were used instead. This PR makes sure that the SQL alchemy string is correct.

fix: override pre-generated database connection

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Learner_Summary_6da509.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Page_Engagement_per_Section_Subsection_29a5cf.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problem_Engagement_per_Section_Subsection_501547.yaml
tutoraspects/templates/openedx-assets/queries/int_problem_results.sql

Fixes:
- At-risk dash: X-axis text rotation to 0 to prevent long block names squashing charts
- Course dash: Problem results / responses charts empty when PII is turned off
- Individual learner: Some missing translations

Dashboard fixes

---

.github/workflows/build-image.yaml

This PR allows to build the images on releases merges

build: build images on releases merges

---

.github/workflows/add-remove-label-on-comment.yml
.github/workflows/integration-test.yml
.github/workflows/release.yaml
.github/workflows/test.yml
tutoraspects/commands_v0.py
tutoraspects/commands_v1.py
tutoraspects/patches/k8s-deployments
tutoraspects/patches/k8s-jobs
tutoraspects/plugin.py

fix: flask debug replaced flask env

---

tutoraspects/patches/openedx-dev-dockerfile-post-python-requirements
tutoraspects/patches/openedx-dockerfile-post-python-requirements
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0036_course_enrollments.py

This PR adds the base table for the course enrollment sink model. See https://github.com/openedx/platform-plugin-aspects/pull/64 for more information.

feat: add course enrollment sink table

---

tutoraspects/plugin.py

Mostly includes bug fixes for clustering & Altinity cloud

Upgrade aspects-dbt to 3.29.1

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0037_remove_most_recent_course_blocks.py

Removes several unused models.

refactor: Upgrade aspects-dbt for performance changes

---

tutoraspects/templates/aspects/build/aspects/requirements.txt

This PR bumps the xapi-db-load version to v1.4

feat(load): bump xapi-db-load to v1.4

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/superset/pythonpath/performance_metrics.py

This PR removes the course-comparison dashboard from the list of embeddable dashboards.

fix(embedded): remove course-comparison dashboard from embeddables

---

tutoraspects/templates/aspects/apps/superset/pythonpath/aspects_asset_list.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Course_Info_b2fff8.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Enrollment_Counts_7eaf5b.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Learner_Performance_Breakdown_b73b0a.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Learner_Performance_b518f3.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_5b00f7.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_6b7610.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Course_Comparison_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/course_information.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/tag_filter.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/watched_video_duration.yaml
tutoraspects/templates/openedx-assets/queries/tag_filter_dataset.sql

Fixes for
1. https://github.com/openedx/openedx-aspects/issues/289
2. "One more with the course comparison dashboard, the tag filter is currently giving me an error message:"  (https://axim-collaborative.slack.com/archives/C07GGRUQS5T/p1729176527571429)

feat: fix enrollment count, fix tag filter, misc updates

---

tutoraspects/templates/aspects/apps/superset/pythonpath/aspects_asset_list.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Course_Info_b2fff8.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Enrollment_Counts_7eaf5b.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Learner_Performance_Breakdown_b73b0a.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Learner_Performance_b518f3.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_5b00f7.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_6b7610.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/course_information.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/tag_filter.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/watched_video_duration.yaml
tutoraspects/templates/openedx-assets/queries/tag_filter_dataset.sql

Reverts openedx/tutor-contrib-aspects#969

Revert "feat: fix enrollment count, fix tag filter, misc updates"

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Course_Info_ccdd7d.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Course_Information_f909e0.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Distribution_of_Course_Grades_cd3479.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Enrollees_by_Enrollment_Track_f8beeb.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Enrollment_Dates_ded618.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Last_Visit_Date_6c2b10.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Learner_Summary_6da509.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Number_of_Views_across_Video_Duration_a7947b.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Page_Engagement_per_Section_Subsection_29a5cf.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Partial_and_Full_Video_Views_2232c3.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Partial_and_Full_Video_Views_54a155.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problem_Attempts_6df964.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problem_Attempts_d3b9fa.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problem_Engagement_per_Section_Subsection_501547.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problem_Results_003e60.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problem_Results_3b70ae.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_5b00f7.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_6b7610.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_8266ce.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_per_Section_Subsection_5d0329.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/At-Risk_Learners.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Course_Comparison_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Course_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Individual_Learner.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_student_status_plus_7_days.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/watched_video_duration.yaml

Fix video count and reset all slice ids

fix: fix aspects dashboards

---

requirements/dev.in

This PR fixes an issue in which the pod-autoscaling dev-requirement was not installed correctly.

chore: update dev requirements

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py

This PR allows to block instructor access to Superset.

feat: allow to block instructor access

---

requirements/dev.in

Fixes failing upgrade action https://github.com/openedx/tutor-contrib-aspects/actions/runs/12624267365/job/35174293727

fix: use pip to install

---

.github/workflows/bump-version.yaml
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py

Custom color scheme for superset. From https://docs.google.com/document/d/1AmLQgpcOx02QycFdeEa77geIY301R16Da9jr56MBpVc/edit?tab=t.0
Colorblind testing results with new colors
https://docs.google.com/document/d/1kiJJrUJqPSID2WItpd9_PaEWq0bAEcplu6xgaJ6jlyQ/edit?tab=t.0

feat: add custom color scheme for data charts

---

tutoraspects/plugin.py

chore: upgrade dbt version

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Final_Response_Results_ab43eb.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Initial_Numeric_Responses_832fc2.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Initial_Responses_f0c87e.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problem_Engagement_8a6f97.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problem_Results_Table_32f16a.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Subsection_Engagement_765e8a.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Subsection_Performance_59e9e2.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Unique_vs._Repeat_Views_0245bc.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_ace4c7.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/In-Context_Analytics_Course.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/In-Context_Analytics_Graded_Subsection.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/In-Context_Analytics_Problem.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/In-Context_Analytics_Video.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/graded_subsection_results.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/graded_subsections.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/problem_results.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/response_breakdown.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/subsection_overview.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/watched_video_segments.yaml
tutoraspects/templates/openedx-assets/queries/graded_subsection_results.sql
tutoraspects/templates/openedx-assets/queries/graded_subsections.sql
tutoraspects/templates/openedx-assets/queries/problem_results.sql
tutoraspects/templates/openedx-assets/queries/response_breakdown.sql
tutoraspects/templates/openedx-assets/queries/subsection_overview.sql
tutoraspects/templates/openedx-assets/queries/watched_video_segments.sql

Adds Superset dashboards for in-context analytics.
Impacts course authors.
<details>
<summary>Course</summary>
</details>
<details>
<summary>Graded Subsection</summary>
</details>
<details>
<summary>Problem</summary>
</details>
<details>
<summary>Video</summary>
</details>
[In-Context Metrics for Studio: Product Requirements](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4694835220/In-Context+Metrics+for+Studio+Product+Requirements)
1. Install this
2. Run `tutor config save`
3. If necessary, rebuild images and import assets as described in README
4. Check the "In Context Analytics" dashboards in http://superset.local.openedx.io:8088/dashboard/list/
9 April 2025
Private-ref: https://tasks.opencraft.com/browse/BB-9637

feat: in-context analytics dashboards

---

tutoraspects/plugin.py

This is the latest LTS from CH, and includes a number of performance improvements, bug fixes, and features including refreshable materialized views.

feat: Upgrade ClickHouse to 25.3

---

README.rst

Updates installation instructions for in-context metrics.

docs: in-context metrics installation instructions
