openedx/tutor-contrib-aspects

README.rst

Updates the README.rst to list out the other plugins OARS depends on and to explain how to enable and initialize them.
Relates to https://github.com/openedx/data-wg/issues/26

docs: updates README

---

tutoroars/templates/oars/apps/pythonpath/superset-dashboard.py

This PR allow to use a superset running on HTTPS for on the init job. It also fixes a bug in which if HTTPS is enabled, the superset set host is never resolved and makes the `tutor local do init --limit oars` command to hang out.
- You can follow the instructions https://github.com/openedx/tutor-contrib-superset/pull/18.
- In the **config.yml** file, set ENABLE_HTTPS to true (point a real domain to the instance you are testing).
- Run `tutor config save`
- Run `tutor local do init --limit oars`
The command should work as expected, without this change the commands hang outs.

fix: use SUPERSET_HOST instead of superset

---

.github/workflows/upgrade-python-requirements.yml

Issue was that the edx-requirements-bot didn't have write access on the repo.

build: Revert debugging changes

---

.github/workflows/test.yml

We are removing the static type checks as those don't add any real value

build: remove unused static type checks

---

tutoroars/plugin.py

This PR pins the version of event-routing-backends

chore: pin event-routing-backends to 5.2.2

---

tutoroars/plugin.py

- Fixes issues in the 5.3.0 release on pre-Palm edx-platform
- Fixes unnecessary retries on duplicate event id's

fix: Upgrade event-routing-backends to 5.3.1

---

setup.py

This PR adds a missing `bcrypt` dependency on install

fix: add missing bcrypt dependency

---

tutoroars/plugin.py
tutoroars/templates/oars/jobs/init/clickhouse/oars_init_schemas_tables_users.sh

PR for [issue #58 ](https://github.com/openedx/tutor-contrib-oars/issues/58)
Creates tables for:
- video playback events
- problem interaction events
- navigation events
The `problem_events` table omits the browser's `problem_check` event from the `problem_events` table. There is a note in the code, but this was primarily because from what I can tell there's nothing in the browser events that isn't in the server events. During my testing, I only came across one instance where browser events where sent without an accompanying server event, and that was when there was a server error (something about my development environment must not be fully set up properly). As a corollary to this, we save a considerable amount of space by only keeping the server events.
I'd love some feedback on the …

feat: create high-level MVs and backing tables (FC-0024)

---

tutoroars/templates/oars/apps/scripts/oars/clickhouse-demo-xapi-data.sh

Fixes an error when running the distributions after load, uses the latest schema.

fix: Upgrade to latest xapi-db-load

---

README.rst
tutoroars/plugin.py
tutoroars/templates/oars/apps/superset/pythonpath/superset_config.py

Allows setting a default language and list of supported languages in Superset. Superset localization seems to be in a fairly poor state, but it's a thing we can help with. This enables us to start testing.

feat: Adds language configuration options for Superset

---

tutoroars/plugin.py
tutoroars/templates/oars/apps/scripts/oars/dbt.sh
tutoroars/templates/oars/apps/scripts/oars/profiles.yml
tutoroars/templates/oars/jobs/init/dbt/init-dbt.sh

Allows us to run the dbt commands using OARS configuration defaults. This currently does a whole build process instead of having it's own image, and uses the head of `main` on https://github.com/openedx/oars-dbt (by default, this is configurable to test branches etc). Neither of these are good long term, but this should help people get started.
`dbt run` will be executed as part of Tutor init.
Test with:
`tutor local do dbt --help `
To see if the project compiles (safe, changes nothing):
`tutor local do dbt -c "compile"`
To run it (generate views, etc) against your Tutor configured ClickHouse:
`tutor local do dbt -c "run"`
Options can also be added, this will run the given model and everything it relies on in dbt, using 4 threads:
`tutor local do dbt -c "run -m +enrollments_by_day …

feat: Add preliminary dbt command support

---

tutoroars/templates/oars/jobs/init/clickhouse/oars_init_schemas_tables_users.sh

Removes `event_type` from top-level event MVs and changes the data type of `verb_id` to `LowCardinality(String)`. As a result of the removal, the MV tables now use `verb_id` in the primary key instead of `event_type`. The data type change should be transparent to users of these tables while improving performance.
I've tested this by running `tutor local do init --limit oars` using my local copy of the repo and confirmed data can still be inserted via `tutor local do load-xapi-test-data`.

feat!: prefer verb_id for primary key in event MVs (FC-0024)

---

tutoraspects/templates/aspects/jobs/init/clickhouse/aspects_init_schemas_tables_users.sh

My apologies for the oversight, but somehow I didn't catch this through all the recent MV changes. I tested this in ClickHouse cloud on the 100M row dataset, as well as locally with data generated by my dev environment.
Fixes an issue with `navigation_events_mv` where the `starting_position` field was not being parsed appropriately. The MV query now:
- parses the field to an `Int16` data type
- defaults to 0 for cases where the field is not expected

fix: smart parsing of starting_position (FC-0024)

---

tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml

Adds Superset assets for the `transcript_usage` and `video_plays` dbt models. There is one dataset and chart for each model and a dashboard containing both charts. The dashboard has two filters: one for `org` and another for `course_id`. The `course_id` filter depends on the `org` filter, and both filters select the first choice by default.
Here is a screenshot of the dashboard:

feat: create instructor dashboard with video data (FC-0024)

---

README.rst
tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/dbt/dbt_project.yml
tutoraspects/templates/aspects/apps/aspects/dbt/packages.yml
tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh

This PR allows installing custom DBT packages
Author concerns:
- Most DBT packages require configuration and changes in the project itself, do not see any reason to add this feature.
- If you want to add a package, fork the repo and modify the project as you need.
- This approach cannot override already existing packages in packages.yml
- Some DBT packages depend on already installed DBT packages, this creates a conflict
- It would be better to override completely the DBT packages file. Waiting for feedback

feat: allow to install extra dbt packages

---

tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
tutoraspects/templates/aspects/apps/superset/pythonpath/queries/dim_course_videos.sql
tutoraspects/templates/aspects/apps/superset/pythonpath/queries/dim_courses.sql
tutoraspects/templates/aspects/apps/superset/pythonpath/queries/fact_enrollments.sql
tutoraspects/templates/aspects/apps/superset/pythonpath/queries/fact_transcript_usage.sql
tutoraspects/templates/aspects/apps/superset/pythonpath/queries/fact_video_plays.sql

There are three significant changes in this PR:
1. The existing `video_plays` and `transcript_usage` datasets are replaced with templated virtual datasets that allow us to join display names into models in a relatively performant way
2. Enrollment charts are added to the instructor dashboard
3. Virtual datasets are added. These are datasets in Superset that rely on a templated SQL query rather than being directly mapped to a table or view in ClickHouse. A new directory is added to (hopefully) make managing those queries easier.
Here is a screenshot of how the dashboard looks (it only has recent local data, hence the very limited visualizations):

feat: use display names for entities instead of ID (FC-0024)

---

README.rst
tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
tutoraspects/templates/aspects/apps/superset/pythonpath/queries/fact_enrollments.sql
tutoraspects/templates/aspects/apps/superset/pythonpath/queries/fact_enrollments_by_day.sql

In addition to adding a chart that shows registered learners per day, there is also a time window that defaults to the last month. I based that filter on the [first screenshot in the Cairn repo](https://github.com/overhangio/tutor-cairn/blob/master/screenshots/courseoverview-01.png).
The time window applies to all charts in the dashboard, but we can restrict it to only certain charts if that's preferred.

feat: add chart for active enrollments per day (FC-0024)

---

tutoraspects/templates/aspects/build/aspects/requirements.txt

This release removes some log spam and introduces the ability to populate the event sink tables for courses and xblocks, which should facilitate more realistic performance testing.

chore: Upgrade xap-db-load to 0.4

---

tutoraspects/templates/aspects/apps/superset/pythonpath/assets.yaml
tutoraspects/templates/openedx-assets/Instructor_dashboard_9.yaml
tutoraspects/templates/openedx-assets/Watched_video_segments_51.yaml
tutoraspects/templates/openedx-assets/dim_course_videos.yaml
tutoraspects/templates/openedx-assets/fact_watched_video_segments.yaml
tutoraspects/templates/openedx-assets/queries/dim_course_videos.sql
tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql

Here is a dataset and dashboard update to show a breakdown of which segments of videos were watched. There is an additional filter, scoped only to the video tab, to select a specific video. Here is a screenshot of the new chart:

feat: add video timeline chart (FC-0024)

---

README.rst
tutoraspects/patches/superset-row-level-security
tutoraspects/templates/aspects/apps/superset/pythonpath/create_row_level_security.py

This PR allows importing extra row-level security filters, which in combination with #123 will allow users to have granular control over what users can see.
- Bootstrap a new dev environment with custom filters
- Call an external API, perform validations, and verify user permissions 
- Use data from some external DB to control which data a user has access to.
- Among others

feat: add support for extra rlsf

---

.github/workflows/release.yaml

This PR pushes the openedx-dev image cache to the registry, which is needed for the test workflow.

build: push openedx-dev cache to registry

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0009_prefer_course_key.py
tutoraspects/templates/openedx-assets/queries/fact_enrollments.sql
tutoraspects/templates/openedx-assets/queries/fact_learner_problem_summary.sql
tutoraspects/templates/openedx-assets/queries/fact_problem_responses.sql
tutoraspects/templates/openedx-assets/queries/fact_transcript_usage.sql
tutoraspects/templates/openedx-assets/queries/fact_video_plays.sql
tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql

Adds an alembic migration to update the materialized view queries. The course key is parsed from the `course_id` field in order to match the data in the `event_sink` tables.
This also updates all the Superset assets to use the new field. I don't think there are any required changes to the dbt models

refactor: parse course key in MV queries (FC-0024)

---

README.rst

- Added instructions to sink pre-existing XAPI data to clickhouse. Since it only starts tracking from the time after aspects is up and running, one might want to be able to see previous data in the charts.
- Added a warning for ```--options "--force"``` in Sink course data from the LMS to clickhouse. One might end up creating duplicate entries in course_overviews if they run it more than once.

docs: Instructions to Sink Historical event data to ClickHouse

---

tutoraspects/commands_v0.py
tutoraspects/commands_v1.py
tutoraspects/patches/local-docker-compose-jobs-services
tutoraspects/templates/aspects/apps/aspects/migrations/README.rst
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0011_vector_replacingmergetree_xapi_raw.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0012_vector_replacingmergetree_xapi_parsed.py
tutoraspects/templates/aspects/apps/vector/file.toml
tutoraspects/templates/aspects/apps/vector/k8s.toml
tutoraspects/templates/aspects/apps/vector/local.toml
tutoraspects/templates/aspects/apps/vector/partials/common-post.toml
tutoraspects/templates/openedx-assets/queries/dim_course_problems.sql
tutoraspects/templates/openedx-assets/queries/dim_course_videos.sql
tutoraspects/templates/openedx-assets/queries/fact_enrollments.sql
tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql

This PR contains a new "tutor do" command to wrap bulk transform of tracking log events so that Vector can capture them, as well as various fixes to make the top level materialized view tables "eventually dedupllicated", which can help in certain edge cases with Ralph bulk import as well.
Right now everything downstream of these tables is a view, and so will pick up deduplication automatically. If we need to start adding other downstream materializations we will need to take this into consideration and make sure to use the "FINAL" keyword or "OPTIMIZE FINAL" in their queries to prevent any duplicate rows trickling downstream.
Closes https://github.com/openedx/tutor-contrib-aspects/issues/127

Fixes for Vector bulk loading

---

tutoraspects/patches/k8s-deployments
tutoraspects/templates/aspects/apps/vector/k8s.toml
tutoraspects/templates/aspects/apps/vector/partials/common-post.toml

This PR fixes an issue with the Vector DaemonSetPermission:
Before this change:
```
2023-07-27T12:19:43.653668Z ERROR vector::internal_events::file::source: Failed reading file for fingerprinting. file=/var/log/pods/san-sebastian-openedx_lms-76b7b5cd4f-n75m6_f3d8bd6f-8f21-4a7c-a9f6-6d87000ae255/lms/0.log error=Permission denied (os error 13) error_code="reading_fingerprint" error_type="reader_failed" stage="receiving" internal_log_rate_limit=true
2023-07-27T14:00:08.514452Z ERROR vector::internal_events::file::source: Failed reading file for fingerprinting. file=/var/log/pods/san-sebastian-openedx_lms-76b7b5cd4f-n75m6_f3d8bd6f-8f21-4a7c-a9f6-6d87000ae255/lms/0.log error=Permission denied (os error 13) error_code="reading_fingerprint" error_type="reader_failed" stage="receiving" …
```

fix: remove security context for vector daemonset

---

tutoraspects/templates/openedx-assets/fact_enrollments.yaml
tutoraspects/templates/openedx-assets/fact_problem_responses.yaml
tutoraspects/templates/openedx-assets/fact_transcript_usage.yaml
tutoraspects/templates/openedx-assets/fact_video_plays.yaml
tutoraspects/templates/openedx-assets/fact_watched_video_segments.yaml
tutoraspects/templates/openedx-assets/xapi_events_all_parsed.yaml

Some Superset assets needed to be updated to match the new DateTime columns

fix: use DateTime instead of DateTime64 for datasets

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0012_vector_replacingmergetree_xapi_parsed.py

ClickHouse materialized views insert data into the target table by referring to column names. However, when inserting data directly into the target table, it relies on column _order_ for the insertion. The query for the materialized views does not have the same ordering of org and course_id as the target table, and so when inserting data the order should be made explicit.

fix: specify insertion order in migration 0012 (FC-0024)

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0011_reorder_mvs.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0013_reorder_mvs.py

Updates the top-level materialized views in the following ways:
1. Adds fields to the `ORDER BY` clause to ensure the entire dataset is migrated during table updates
2. Truncates `emission_time` from `DateTime64(6)`, which stores nanosecond granularity, to `DateTime`, which stores second granularity
3. Stores video positions as `UInt32` (via `Decimal32(2)`) to avoid the imprecise `Float32` type

feat!: reorder MVs and change data types (FC-0024)

---

tutoraspects/templates/openedx-assets/queries/fact_enrollments_by_day.sql

We're no longer using such high-precision timestamps for emission_time in the MVs. This should be the last issue related to the timestamp change.

fix: update timestamp type in enrollment_by_day (FC-0024)

---

tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql

There was a missing join key that caused duplicate rows to be returned as part of the video timeline query. This resulted in inflated metrics for watched video segments.

fix: deduplicate video timeline events (FC-0024)

---

tutoraspects/templates/aspects/build/aspects/requirements.txt

Now that xapi-db-load has a new release, let's use it in this plugin!

chore: bump xapi-db-load to 0.5 (FC-0024)

---

README.rst

The current links point to an old location of the Superset assets.

docs: update virtual dataset links in README (FC-0024)

---

tutoraspects/templates/aspects/build/aspects/requirements.txt

Makes fake data more realistic, allows date configuration and reduces the default date span from 10 yrs to 1.

chore: Upgrade xapi-db-load to 0.6

---

tutoraspects/templates/openedx-assets/Instructor_dashboard_9.yaml
tutoraspects/templates/openedx-assets/queries/fact_enrollments_by_day.sql

This addresses #246. The query for `fact_enrollments_by_day` is also updated to extend the current enrollment status window to tomorrow so that the current days' enrollment status is included, which in turn makes the enrollment status available for the chart. In that same query, I've also confirmed that the call to `lagInFrame` provides a default value and so the call to `coalesce` further down is not needed.

feat: include current day in instructor dashboard (FC-0024)

---

tutoraspects/templates/openedx-assets/queries/dim_course_problems.sql
tutoraspects/templates/openedx-assets/queries/dim_course_videos.sql
tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql

This fixes #258. The `where_in` jinja filter will add parentheses automatically. Since this macro was wrapped in parentheses in a few places, it caused an issue when more than one filter value was selected (though apparently it was fine when only one value was selected).

fix: remove extra parens from dashboard filters (FC-0024)

---

tutoraspects/plugin.py

Fixes an issue with unicode in course names and blocks causing course sync to fail.

chore: Upgrade openedx-event-sink-clickhouse to 0.1.1

---

tutoraspects/plugin.py

This PR upgrade ERB to 5.5.4. Includes the following fixes:
[fix: catch null weighted_possible](https://github.com/openedx/event-routing-backends/commit/4a66fb02dc5a08e5945fff623391ae42fbcd39d9)
[fix: Divide by 0 errors on problem interaction events](https://github.com/openedx/event-routing-backends/commit/71d364ade573f472721748bf9c50c4b4dafb7b4c)
[feat: upgrade to Django 4.2](https://github.com/openedx/event-routing-backends/commit/cf7fa198378cadd658925b925ab77ec202dee2b2)
[fix: Caliper transform of video events without duration](https://github.com/openedx/event-routing-backends/commit/bc672fb3235de28db43025ed4c897c2c57d334c9)

fix: upgrade event-routing-backends to 5.5.4

---

tutoraspects/plugin.py

Retries failed download chunks in bulk transform.

chore: Upgrade event-routing-backends to 5.5.5

---

tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
tutoraspects/templates/aspects/apps/superset/pythonpath/locale.yaml

This PR corrects the translation implementation so that previous defined translations are not overwritten by new translations
Fixes https://github.com/openedx/tutor-contrib-aspects/issues/273

fix: use yaml delimiter to separate translations

---

tutoraspects/patches/k8s-volumes
tutoraspects/plugin.py

This PR creates a setting to allow to control the clickhouse volume size: `CLICKHOUSE_VOLUME_SIZE`

fix: add configurable clickhouse volume size

---

tutoraspects/commands_v0.py
tutoraspects/commands_v1.py

**Description:**
This pull request introduces a series of click options to the transform_tracking_logs command, enhancing its versatility and user-friendliness.
**Objective:**
The primary goal of these additions is to provide a clearer and more structured way for users to interact with the transform_tracking_logs command. By allowing explicit configuration via command-line options, we make the functionality more transparent and easier to customize.
Changes Made:
- Refactored to utilize kwargs, simplifying the command signature.
- Enhanced readability by breaking long input into many @click.option.
**How to Test:**
The command can be tested by running something like this:
```
`tutor k8s do transform-tracking-logs \
--source_provider LOCAL \
--source_config '{"key": "/openedx/data/", …
```

fix: Adapted transform_tracking_logs command for enhanced CLI integration

---

.github/workflows/test-tutor-aspects.yml

This PR fixes an issue in which the locally built images were not used for the k8s testing.
This PR also ignores changes for `CHANGELOG.md`, `setup.cfg` and `tutoraspects/__about__.py` to disable this workflow for the release PR.

test: load images built in kind

---

tutoraspects/templates/openedx-assets/assets/dashboards/Instructor_dashboard.yaml

This splits the problem and video tabs into course-level and component-level tabs. Additionally, the problem name and course name filters only act on the component-level tabs and are now required.
I would appreciate feedback on the tab names, which are currently: course problem engagement, problem performance, video engagement, video drilldown. I don't think these are perfect, but I wanted to choose something to keep the PR moving.
Screenshots:

feat: create component-specific tabs (FC-0033)

---

tutoraspects/templates/openedx-assets/assets/charts/Attempts_to_first_success.yaml

The "attempts to first success" chart was not filtering out unsuccessful responses. This change updates the chart to only look at successful responses and show the number of attempts before submitting a correct response.

fix: filter out unsuccessful responses in "attempts to first success" chart (FC-0033)

---

tutoraspects/templates/openedx-assets/assets/datasets/fact_enrollments.yaml
tutoraspects/templates/openedx-assets/assets/datasets/fact_enrollments_by_day.yaml
tutoraspects/templates/openedx-assets/assets/datasets/fact_learner_problem_summary.yaml
tutoraspects/templates/openedx-assets/assets/datasets/fact_problem_responses.yaml
tutoraspects/templates/openedx-assets/assets/datasets/fact_transcript_usage.yaml
tutoraspects/templates/openedx-assets/assets/datasets/fact_video_plays.yaml
tutoraspects/templates/openedx-assets/assets/datasets/fact_watched_video_segments.yaml
tutoraspects/templates/openedx-assets/assets/datasets/hints_per_success.yaml
tutoraspects/templates/openedx-assets/queries/common_filters.sql
tutoraspects/templates/openedx-assets/queries/fact_enrollments.sql
tutoraspects/templates/openedx-assets/queries/fact_enrollments_by_day.sql
tutoraspects/templates/openedx-assets/queries/fact_learner_problem_summary.sql
tutoraspects/templates/openedx-assets/queries/fact_problem_responses.sql
tutoraspects/templates/openedx-assets/queries/fact_transcript_usage.sql
tutoraspects/templates/openedx-assets/queries/fact_video_plays.sql
tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql
tutoraspects/templates/openedx-assets/queries/hints_per_success.sql

This change brings back virtual datasets so that we can use the course name dashboard filter to leverage the index on `course_key` in ClickHouse. There doesn't appear to be a straightforward way to allow users to pick from course names in the dashboard while using the course key in our queries, so virtual datasets are the only way for us to leverage the `course_key` index.
I've run this locally and confirmed that the dashboard results are the same as using the dbt models directly.

refactor: use course_key index in dashboard queries (FC-0033)

---

tutoraspects/patches/superset-row-level-security

This adds row-level security filters for datasets created from dbt models by applying the existing `can_view_course` macro. The schema is listed as `None` as that is what appears for the schema attribute when working with the Superset library. I've tested that these policies are created as expected but I am still working on confirming that they are applied when a user has neither the `Admin` nor `Alpha` roles.

feat: add RLS filters for dbt models (FC-0033)

---

tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py

This PR adds a cache wrapper for the `can_view_courses` function. The cache can be configured using the superset `data_cache`
It also removes the caching for the `get_courses` function such that people will get the latest courses at login.

fix: add cache wrapper for can_view_courses filter

---

README.rst
tutoraspects/commands_v0.py
tutoraspects/commands_v1.py
tutoraspects/templates/aspects/jobs/init/clickhouse/deduplicate.sh

This PR adds a `deduplicate` option for the `transform_tracking_log` command that will run the `OPTIMIZE table FINAL` for every table that needs it.
Fixes #300

fix: add option to deduplicate tables after backfill

---

tutoraspects/plugin.py

This PR upgrades `event-routing-backends` to 5.6.0

feat: upgrade event-routing-backends to 5.6.0

---

tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
tutoraspects/templates/openedx-assets/assets/dashboards/Instructor_dashboard.yaml

This change includes the language code in the default text of a translated asset. This would make it easier to identify the canonical version of assets, such as the instructor dashboard, that should be modified and exported when making changes.

feat: include language code in translated asset name (FC-0033)

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0015_add_course_key_blocks.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0017_add_graded_course_block_names.py

This adds the newly-available `graded` boolean to the course blocks metadata. I meant to add this during the previous migration upgrade and I was hoping that little enough time had passed that we could sneak this change in, but I can create a new migration if that's preferred.

feat: add graded boolean to course_block_names (FC-0033)

---

tutoraspects/templates/openedx-assets/assets/charts/Grade_distribution_courses.yaml
tutoraspects/templates/openedx-assets/assets/charts/Grade_distribution_problems.yaml
tutoraspects/templates/openedx-assets/assets/charts/Problem_submission_counts.yaml
tutoraspects/templates/openedx-assets/assets/dashboards/Instructor_dashboard.yaml
tutoraspects/templates/openedx-assets/assets/datasets/fact_learner_problem_course_summary.yaml
tutoraspects/templates/openedx-assets/queries/fact_course_grades.sql
tutoraspects/templates/openedx-assets/queries/fact_learner_problem_course_summary.sql
tutoraspects/templates/openedx-assets/queries/fact_learner_problem_summary.sql
tutoraspects/templates/openedx-assets/queries/fact_problem_grades.sql
tutoraspects/templates/openedx-assets/queries/fact_problem_responses.sql
tutoraspects/templates/openedx-assets/queries/fact_transcript_usage.sql
tutoraspects/templates/openedx-assets/queries/fact_video_plays.sql
tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql
tutoraspects/templates/openedx-assets/queries/int_problem_responses.sql

For course- and component-scoped datasets, limit the results of a query when filter values are absent. This will prevent returning a lot of data in a way that could be confusing for users.
Here are two screenshots of the problem performance tab that shows the default view and the view when a specific problem is selected:

feat: limit data returned when filters are absent (FC-0033)

---

tutoraspects/patches/k8s-jobs
tutoraspects/templates/aspects/jobs/init/superset/init-superset.sh

This PR fixes an issue in the superset job that makes the init script unable to create folders

fix: set security context for superset job

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py

Closes #353 
This setting seems to have been reversed from what we want. It was causing Superset SSO to fail in tutor local HTTPS environments due to Superset not knowing it was proxied behind HTTPS and sending an incorrect "http://" redirect instead of "https://".

fix: Enable Superset proxy fix when Caddy is on

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0019_forum_events_mv.py

This adds a new top-level materialized view for forum events. This set of fields should cover our existing use cases so I didn't want to add anything else until we had a better idea of the requirements, but please let me know if there's anything else that could be included at this point.

feat: add materialized view for forum events (FC-0033)

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0020_get_org_from_course_url.py

The old get_org_from_course_url function was not working correctly as it was omitting text that included some of the following chars: `-~.:%`
We are using the deprecated version as it's a superset of the actual version and it will allow us to support very old courses
This was extracted from: https://github.com/openedx/opaque-keys/blob/e0ee525df4395f3795501fdc3a75a7ecdbedcb1f/opaque_keys/edx/locator.py#L46-L47

fix: update the get org from url function to include other chars

---

tutoraspects/patches/k8s-deployments
tutoraspects/patches/k8s-jobs

This PR fixes an error in which Ralph was receiving the wrong variable name for the Clickhouse database.
Extracted from here: https://github.com/openfun/ralph/blob/a42dbae8c4fd856aca6ac1cd555d381712ed80f6/tests/test_cli.py#L918

fix: update ralph clickhouse database name in k8s

---

tutoraspects/patches/k8s-deployments
tutoraspects/patches/k8s-volumes

This PR uses a local volume for the Vector DaemonSet instead of a emptyDir volume

fix: use local volume instead of emtpy dir for vector data

---

tutoraspects/plugin.py

This PR upgrades event-routing-backends to 6.2.0.
Full changelog: https://github.com/openedx/event-routing-backends/compare/v5.6.0...v6.2.0

feat: upgrade event-routing-backends to 6.2.0

---

tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py

This fixes an issue in small installations where if the permissions were granted after the user login to Superset, superset will cache forever the missing permissions and the server needs to be restarted
Fixes: https://github.com/openedx/tutor-contrib-aspects/issues/406

fix: remove cache for get_courses

---

.github/workflows/compile-translations.yaml

This PR updates the translation workflow to include only changes in Aspects and not in CI. See https://github.com/openedx/tutor-contrib-aspects/pull/450#discussion_r1350391139 for more information

chore: only include aspects changes in translation workflow

---

tutoraspects/templates/openedx-assets/assets/charts/Distinct_forum_users.yaml
tutoraspects/templates/openedx-assets/assets/charts/Posts_per_user.yaml
tutoraspects/templates/openedx-assets/assets/dashboards/Instructor_Dashboard.yaml
tutoraspects/templates/openedx-assets/assets/datasets/fact_forum_interactions.yaml
tutoraspects/templates/openedx-assets/assets/datasets/posts_per_user.yaml
tutoraspects/templates/openedx-assets/queries/fact_forum_interactions.sql
tutoraspects/templates/openedx-assets/queries/posts_per_user.sql

This change adds a forum interaction tab to the instructor dashboard and includes two new charts: the number of active forum users and the number of posts per user.
Here is a screenshot of the new tab:

feat: add forum interaction tab (FC-0033)

---

tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py

This PR implements add two new patches:
- `superset-config`: Allow to add/override Superset production config
- `superset-config-docker`: Allow to add/override Superset docker config

feat: add tutor patches for superset config

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0023_extend_display_names.py

Addresses #436 
To give dashboard users more context when looking at block names, the location of the block is prepended to the display name of the block. This PR introduces a new table, `most_recent_course_blocks`, that is populated by a materialized view that will insert the most recent version of a block. The `course_block_names` dictionary is updated to use this table instead of querying `event_sink.course_blocks` directly.

feat: add location to block display names (FC-0033)

---

tutoraspects/templates/openedx-assets/queries/fact_learner_problem_course_summary.sql

The "Responses Per Problem" chart on the problem engagement tab does not respond to the datetime filters. This PR adds those filters to the templated query powering the chart so that it may accurately reflect the chosen filters.

fix: consistently apply datetime filter on problem engagement tab (FC-0033)

---

tutoraspects/plugin.py
tutoraspects/templates/openedx-assets/queries/fact_learner_problem_summary.sql
tutoraspects/templates/openedx-assets/queries/fact_problem_responses.sql

Addresses #479 
This change updates the "Distribution of Responses" chart to show each choice individually for multiple-choice problems. This also fixes a bug with the problem-level learner summary model exposed by accommodating problems with multiple parts.
Here is a screenshot of the chart with the new query:

feat: display multiple-choice answers separately (FC-0033)

---

Makefile
scripts/utils.py
tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/superset/conf/locale/fr_CA/locale.yaml
tutoraspects/templates/aspects/apps/superset/localization/locale.yaml
tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py
tutoraspects/templates/aspects/apps/superset/security/roles.json

This PR updates the pull_translations workflow to use Atlas and the openedx-translations repository. It also uses the existing Open edX supported language/locale codes for our translations, as that's what the translations working group uses. Superset itself will still only have top level languages.

refactor: Use new Transifex / Atlas pipeline to pull loc

---

scripts/utils.py
tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_jinja_filters.py
tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py
tutoraspects/templates/openedx-assets/assets/dashboards/Instructor_Dashboard.yaml
tutoraspects/templates/openedx-assets/assets/dashboards/Operator_Dashboard.yaml
tutoraspects/templates/openedx-assets/assets/databases/OpenedX_Clickhouse.yaml
tutoraspects/templates/openedx-assets/assets/datasets/course_blocks.yaml
tutoraspects/templates/openedx-assets/assets/datasets/course_names.yaml
tutoraspects/templates/openedx-assets/assets/datasets/course_overviews.yaml
tutoraspects/templates/openedx-assets/assets/datasets/xapi_events_all_parsed.yaml

Fixes for permissions cache and localization issues

---

scripts/utils.py

Previously the strings would be translated if they existed in the locale file, but the filter names weren't being pulled into Transifex.

fix: Pull filter names as translatable strings

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0024_escape_problem_responses.py

Fixes #494 by escaping single quotes and replacing double quotes with single quotes in problem responses. This allows problem responses to be successfully parsed as arrays. Below is a screenshot of answers with single quotes being displayed in the problem performance tab:

feat: replace double quotes in problem responses (FC-0033)

---

README.rst
scripts/translate_utils.py

This path change got missed in the assets refactor, causing source strings to be deleted in Transifex.

fix: Change translations source path

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Instructor_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Operator_Dashboard.yaml

Moves the lengthy text descriptions out of the Dashboards and Charts and replaces them with deep links into the openedx-aspects reference documentation.
The Help markdown is configurable for each of the Operator and Instructor Dashboards, or the Help tab(s) may be omitted entirely by setting:
```
tutor config save -s ASPECTS_INSTRUCTOR_HELP_MARKDOWN=""
tutor config save -s ASPECTS_OPERATOR_HELP_MARKDOWN=""
```
ref https://github.com/openedx/tutor-contrib-aspects/issues/169
Related to https://github.com/openedx/openedx-aspects/pull/100

refactor: replaces dashboard tab docs with link to openedx-aspects docs

---

tutoraspects/patches/k8s-deployments

Updates the k8s configuration to use Tutor variables when exposing the Clickhouse container ports.
Closes https://github.com/openedx/tutor-contrib-aspects/issues/387

fix: use tutor variables to expose clickhouse container ports in k8s

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Events_per_course.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Most_Active_Courses_Per_Day.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Operator_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/xapi_events_all_parsed.yaml

Adds a computed `course_key_short` field to the `xapi_events_all_parsed` dataset, which strips the `course-v1:` prefix off of the beginning of the `course_key`.
Modifies the charts under the Operator > Courses tab to use `course_key_short` instead of `course_key` as the groupby/label.
Also re-adds the "Events per Course" chart to the Operator tab -- it must have gotten removed accidentally by https://github.com/openedx/tutor-contrib-aspects/pull/515?
Closes https://github.com/openedx/tutor-contrib-aspects/issues/245

Use shortened course key on Operator Course charts

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0026_event_sink_external_id.py

This adds a table for the external_id sink defined here https://github.com/openedx/openedx-event-sink-clickhouse/pull/43

feat: add external id table

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Operator_Dashboard.yaml

This change updates the operator dashboard to use the `course_names` datatset for course name and course run filters, which performs better than using the `fact_enrollment_by_day` dataset.
This should address the "Filters on Enrollments tab" item in #535

feat: use `course_names` for operator dashboard filters

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/dbt/profiles.yml
tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh
tutoraspects/templates/aspects/jobs/init/aspects/init-aspects.sh

This change pulls in the latest changes to aspects-dbt, which includes support for writing MVs to a custom schema. This reinstates the existing functionality where MVs were written to the `xapi` schema instead of `reporting`.

fix: write MVs to xapi schema (FC-0033)

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Courses.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Total_Organizations.yaml

This change updates the "Total Courses" and "Total Organizations" charts in the operator dashboard so that they use the smaller `event_sink.course_names` dataset. This should help with the performance issues mentioned in #535. Both charts still work with the `course_key` filter applied.

feat: prefer `course_names` for courses and organizations charts in operator dashboard (FC-0033)

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0016_event_sink_user_profile.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0026_event_sink_external_id.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0027_partition_event_sink_user_profile.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0028_user_pii.py

Adds PII annotation docstrings to the PII tables created by Aspects.
Relates to https://github.com/openedx/openedx-aspects/pull/106
Reference: [OEP-30 PII Markup and Auditing](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0030-arch-pii-markup-and-auditing.html#docstring-annotations)

docs: annotates the PII tables in Aspects as per OEP-30

---

README.rst

Without this step we no longer create the correct assets, and Superset is full of errors.

docs: Update readme to include building Superset image

---

README.rst
tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py

This PR allows developers to not need to build the Superset image if the assets and other settings match the defaults. This allows to easily tests Aspects without the need to build the Superset image on any single change

fix: import databases from settings

---

setup.py
tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/dbt/profiles.yml

We've removed the JSON column, so we can pull these settings, except in the old migrations.

refactor: Remove refs to ClickHouse allow_experimental_object_type

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh
tutoraspects/templates/aspects/jobs/init/aspects/init-aspects.sh

This PR adds a new setting to allow to setup an SSH key to clone private DBT repositories. Fixes #578 
This has been tested only on `github.com`.

fix: allow to setup private dbt repository

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0032_partition_tables_by_year_and_month.py

Partition the `xapi_events_all` table by year and month.

feat: partition xapi_events_all table

---

.github/workflows/integration-test.yml
README.rst
tutoraspects/commands_v0.py
tutoraspects/commands_v1.py
tutoraspects/plugin.py

This PR replaces the `dump-courses-to-clickhouse` with the `dump-data-to-clickhouse` command and upgrades the `openedx-event-sink-clickhouse` version to `v1.1.0`

feat: add command to dump data to clickhouse

---

.github/workflows/bump-version.yaml
.github/workflows/integration-test.yml
.github/workflows/pull-translations.yaml
.github/workflows/release.yaml
.github/workflows/test.yml
setup.py
tutoraspects/commands_v0.py
tutoraspects/templates/aspects/build/aspects/Dockerfile

Python 3.8 is nearing end of life, and we're using a bunch of different versions of Python in the various tooling and Aspects image in this repo. This is just consolidating everything to 3.12 so we don't have to worry about it again for a few years.

chore: Update python to 3.12 wherever possible

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh
tutoraspects/templates/aspects/jobs/init/aspects/init-aspects.sh

Removes an unnecessary variable, and removes duplicated code from our init scripts.
Done while working on https://github.com/openedx/openedx-aspects/issues/73.

Removes DBT_REPOSITORY_PATH

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0033_ccx_function.py

This PR creates a new function to extract the org from the ccx course URL.
See https://github.com/openedx/aspects-dbt/pull/44 for more information

feat: add get_org_from_ccx_course_url function

---

tutoraspects/templates/aspects/apps/superset/security/roles.json

This PR grants the necessary permissions for the Public role to use an embedded dashboard in the LMS and to download the CSV report. The Public role is the one used to determine the guest tokens permissions which are used to embed the dashboards in the LMS Instructor Dashboard.
You can read more information about the Superset Public role here: https://superset.apache.org/docs/security/#public. It's safe to assign those permissions as we are using the Dashboard RBAC feature and to grant access to the data itself we would need to grant permissions over the datasets.

feat: grant permissions to embed dashboard to Public role

---

.github/workflows/release.yaml

This PR fixes an issue with the build steps of CI to only update the ASPECTS_VERSION in PRs

chore: only update aspects version on PR builds

---

requirements/base.in

When installed with old Tutor versions this requirement isn't included and causes errors.

fix: Add importlib-resources to base requirements

---

tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py

Some assets have a description instead of a name, so we now check that as well and fail with a clearer error if neither exists.
Closes: https://github.com/openedx/tutor-contrib-aspects/issues/626

fix: Some dashboard assets do not have a name to localize

---

.github/workflows/integration-test.yml
tutoraspects/commands_v0.py
tutoraspects/commands_v1.py
tutoraspects/patches/k8s-jobs
tutoraspects/patches/k8s-volumes
tutoraspects/patches/local-docker-compose-jobs-services
tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh
tutoraspects/templates/aspects/jobs/init/aspects/init-aspects.sh

This is a work in progress to avoid rebuilding our large materialized views when we can avoid it. This dbt feature is complicated and requires storing the state of the last run so it can decide what's changed. 
Closes: https://github.com/openedx/tutor-contrib-aspects/issues/546
Open questions:
- How to work around this option being automatically added for commands that it doesn't make sense for (maybe just document that it needs to be turned off for them?)
- Is a k8s PVC the right way to go to store the state there?
- Are there other ways to surface that this is happening, or is some documentation enough
- What things should we consider safe to ignore for "changed" state? Tests, probably. Anything else? https://docs.getdbt.com/reference/node-selection/state-comparison-caveats

feat: Use dbt state to avoid large table rebuilds

---

tutoraspects/plugin.py

This PR upgrades dbt to v3.9.0:
- video duration to playback events.
- add graded and block_type to dim_course_blocks.
- add fact_grade_status model.
- include models for pageview engagement.

feat: upgrade dbt to v3.9.0

---

scripts/translate_utils.py
tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/ab_user.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/clickhouse_computed_metrics.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/course_blocks.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/course_names.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/course_overviews.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/dashboards.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/dim_course_problems.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/dim_course_videos.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_course_grades.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_enrollments.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_enrollments_by_day.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_forum_interactions.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_learner_problem_course_summary.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_learner_problem_summary.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_problem_grades.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_problem_responses.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_transcript_usage.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_video_plays.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_watched_video_segments.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/hints_per_success.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/indexed_events.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/posts_per_user.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/slices.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/slowest_clickhouse_queries.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/superset_action_log.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/user_pii.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/xapi_events_all_parsed.yaml

This PR allows translating columns and metrics names from the datasets. It doesn't affect the queries as the value changed is only the `verbose_name`.
A new dataset is created for every supported language and associated with the corresponding chart.

feat: add dataset columns/metrics translation support

---

.github/workflows/release.yaml
tutoraspects/patches/openedx-common-settings
tutoraspects/patches/openedx-development-settings
tutoraspects/plugin.py

Updates the dependencies and settings related to https://github.com/openedx/platform-plugin-aspects/pull/7
0. Install this branch to your Tutor virtualenv, and ensure this plugin is enabled.
1. (optional) change the default dashboard: `tutor config save -s ASPECTS_INSTRUCTOR_DASHBOARD_UUID=a4472382-0cb4-4874-8fd9-5eb42aadbf11`
2. Rebuild the openedx image (or `openedx-dev` if running Tutor dev): `tutor images build openedx --no-cache`
3. Restart openedx to use the new image: `tutor [dev|local] stop lms cms lms-worker cms-worker && tutor [dev|local] start -d lms cms lms-worker cms-worker`
4. Create a new course in Studio
5. Add `"superset"` to the Settings > Advanced Settings > Advanced Module List
6. Add a new section, subsection, unit
7. Add a Advanced > Superset Dashboard block to the …

Upgrades platform-plugin-aspects and enables Instructor Dashboard plugin

---

tutoraspects/patches/openedx-common-settings
tutoraspects/plugin.py

See https://github.com/openedx/platform-plugin-aspects/pull/9 for more information.
Waiting on `platform-plugin-aspects==0.3.1` to be released

fix: remove internal_service_url from production settings

---

.github/workflows/build-image.yaml
.github/workflows/release.yaml

This PR separates the `build` job and the `release` job. It also prevents the `build` job to run when the PR is from a bot.

build: do not build images on bot PRs

---

tutoraspects/templates/aspects/apps/vector/partials/common-post.toml

This PR fixes an issue with vector in which the xapi logs were sent to the event_str field, which no longer exists.

fix: send event as str from vector to the 'event' field

---

.github/workflows/build-image.yaml

This PR push the latest image when needed on CI.
This has been tested in CI, by disabling checks so images are already pushed.
- Run: `docker pull edunext/aspects:latest` and the image should be downloaded

build: push latest image on CI

---

tutoraspects/patches/openedx-dockerfile-post-python-requirements
tutoraspects/plugin.py

Uses a [patch to add extra python requirements to Open edX](https://github.com/overhangio/tutor/blob/f211b982fd8d970a538eb8452e16259a5eaae92b/tutor/templates/build/openedx/Dockerfile#L116-L117) instead of using the `OPENEDX_EXTRA_PIP_REQUIREMENTS` variable.
I've been running into issues with using Aspects with other Tutor plugins that also overwrite `OPENEDX_EXTRA_PIP_REQUIREMENTS `, and someone on my team suggested this patch approach.
This change allows Tutor operators to use this variable to override or add their own extra requirements without disrupting Aspects.
**Testing instructions**
Rebuild your `openedx(-dev)` image using this branch.
Note that the platform-plugin-aspects and edx-event-routing-backends packages get installed as expected.

refactor: moves the openedx pip requirements into a patch

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Pageview_engagement_by_section_subsection.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Instructor_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_pageview_engagement.yaml
tutoraspects/templates/openedx-assets/queries/fact_pageview_engagement.sql

This PR adds a dataset that can be used to show the number of learners who have:
1. viewed at least one page in a section or subsection
2. viewed all pages in a section or subsection
This is still a draft because I wanted to give a more elaborate example of how I imagined using the models added in [my recent aspects-dbt PR](https://github.com/openedx/aspects-dbt/pull/52).
Here is a chart that I made from this dataset:

feat: add dataset for pageview engagement charts (FC-0051)

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh

and bump aspects-dbt branch to [v3.9.1](https://github.com/openedx/aspects-dbt/releases/tag/v3.9.1) to fix dbt-core dependency issue (https://github.com/dbt-labs/dbt-core/issues/9759).
```
tutor dev|local config save
tutor dev|local do dbt -c "run"
```

fix: install aspects-dbt package requirements before running dbt

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/jobs/init/clickhouse/init-clickhouse.sh
tutoraspects/templates/openedx-assets/queries/fact_enrollments.sql
tutoraspects/templates/openedx-assets/queries/fact_learner_problem_summary.sql
tutoraspects/templates/openedx-assets/queries/fact_pageview_engagement.sql
tutoraspects/templates/openedx-assets/queries/int_problem_responses.sql

This PR upgrades the ClickHouse version to 24.3. As the new query analyzer is enabled by default, it will try to parse every query and will fail to do so when there is a nested `with` using the same name, so SQL queries are updated with the prefix `base`.
Depends on: https://github.com/openedx/aspects-dbt/pull/59

feat: upgrade to clickhouse 24.3 LTS

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_engagement_by_section_subsection.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Instructor_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_video_engagement.yaml
tutoraspects/templates/openedx-assets/queries/fact_video_engagement.sql

This adds a dataset and chart for video engagement dropoff, modeled after the dataset and chart added in #673. This relies on the models in an [accompanying PR to aspects-dbt](https://github.com/openedx/aspects-dbt/pull/61).

feat: add dataset and chart for video engagement dropoff (FC-0051)

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problem_engagement_by_section_subsection.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Instructor_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_problem_engagement.yaml
tutoraspects/templates/openedx-assets/queries/fact_problem_engagement.sql

This adds a chart to the instructor dashboard that shows the number of learners who attempted problems within a section or subsection.

feat: add problem engagement dropoff chart to instructor dashboard (FC-0051)

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Partial_and_full_views_per_video.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Instructor_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_video_watches.yaml
tutoraspects/templates/openedx-assets/queries/fact_video_watches.sql
tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql

This adds a chart to show the number of full and partial views of course videos. This builds on the watched video segments query and compares the number of segments viewed by a learner to the expected number of segments in the video. The number of segments is calculated by first taking ten seconds off the video duration and then calculating the number of segments based on that shortened duration. This is to account for learners who, say, watch the entire video but skip the end credits.
Here is a screenshot of the chart:

feat: add chart for full and partial video views (FC-0051)

---

tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
tutoraspects/templates/aspects/apps/superset/pythonpath/create_row_level_security.py
tutoraspects/templates/aspects/jobs/init/superset/init-superset.sh

This PR automatically creates RLSF for all tables with options to exclude tables from the filters. The filters are grouped by database.

fix: automatically add RLSF to all tables

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh

This PR creates a setting: `ASPECTS_DATA_TTL_EXPRESSION` to configure the TTL of partitioned tables in `aspects-dbt`.
Example:
```
1. │ CREATE TABLE xapi.completion_events
(
`event_id` UUID,
`emission_time` DateTime,
`actor_id` String,
`object_id` String,
`course_key` String,
`org` String,
`verb_id` String,
`progress_percent` String
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMM(emission_time)
PRIMARY KEY (org, course_key, verb_id)
ORDER BY (org, course_key, verb_id, emission_time, actor_id, object_id, event_id)
TTL toDateTime(emission_time) + toIntervalYear(1)
SETTINGS replicated_deduplication_window = 0, index_granularity = 8192
```

feat: add configurable TTL

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/dbt/profiles.yml
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0035_migrate_dictionaries.py
tutoraspects/templates/aspects/apps/aspects/scripts/dbt.sh
tutoraspects/templates/aspects/build/aspects/requirements.txt

This PR drops all dictionaries, related tables, and MVs in favor of DBT dictionary definitions.
Depends on: https://github.com/openedx/aspects-dbt/pull/60

feat: migrate aspects dictionaries to dbt

---

tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py

This PR refactors the process_asset logic into a separate function.

chore: refactor process_asset logic

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Page_views_per_section_subsection.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problems_attempted_per_section_subsection.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_views_per_section_subsection.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Course_Dashboard_V1.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_problem_engagement.yaml

This change updates the page view, problem, and video engagement charts to use the correct dataset for each. The existing charts used fake data for the purposes of mocking the expected design and behavior and needed to be updated to show accurate data.

fix: use correct datasets for engagement charts (FC-0051)

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_views_by_section_subsection.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Course_Dashboard_V1.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_video_plays.yaml

This change adds a table to the video engagement tab of the course dashboard. This table shows the number of views each video has, along with the videos section and subsection name. This is to give dashboard viewers more context as to which videos are included in the accompanying "video views per section/subsection" graph.
Here is a screenshot of the table:

feat: add video plays table to course dashboard (FC-0051)

---

tutoraspects/patches/openedx-dev-dockerfile-post-python-requirements
tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py
tutoraspects/templates/aspects/apps/superset/pythonpath/performance_metrics.py

Fixes an issue where dashboards do not load in the LMS instructor dashboard due to query_context containing database primary keys from the database it was exported from. Performance metrics uses the query_context, so now it pulls that directly from the asset files on disk instead.

fix: Remove query context after asset import

---

tutoraspects/plugin.py
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Partial_and_full_views_per_video.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_views_by_section_subsection.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Course_Dashboard_V1.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_pageview_engagement.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_video_engagement.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_video_plays.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_video_watches.yaml
tutoraspects/templates/openedx-assets/queries/fact_pageview_engagement.sql
tutoraspects/templates/openedx-assets/queries/fact_video_engagement.sql
tutoraspects/templates/openedx-assets/queries/fact_video_watches.sql
tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql

This change ensures that charts display the expected behavior for various filters applied in the course dashboard. This includes:
- all video charts responding to section and subsection filters
- the page view engagement chart applies section and subsection filters
- the partial and full video views chart uses the correct dataset in addition to using the appropriate filters
This change also includes edits made by running `sqlfmt` on changed SQL files.

fix: apply filters to course dashboard datasets (FC-0051)

---

tutoraspects/patches/openedx-dev-dockerfile-post-python-requirements
tutoraspects/patches/openedx-dockerfile-post-python-requirements

This has a fix for xblock imports in pre-quince deployments.

chore: Bump platform-plugin-aspect to 0.9.1

---

.github/workflows/build-image.yaml
.github/workflows/bump-version.yaml

This PR prevents the bump version workflow from running automatically. Now, it needs to be manually run and select a the type of bump: `major`, `minor` or `patch`.

chore: bump version manually

---

tutoraspects/patches/openedx-common-settings

This PR fixes a compatibility issue with pre quince environment where the `EVENT_BUS_PRODUCER_CONFIG` variable is not defined

fix: verify event bus producer config is defined

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Watched_Video_Segments.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Watched_Video_Segments_at-risk.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_watched_video_segments.yaml

This change prefers the `segment_start` field, which is the start time of the video segment watched by a learner.
Here is a screenshot, which also includes the new axis labels:
Before this change, the chart would have grouped each segment under "0"

fix: show correct value on watched segments x-axis (FC-0051)

---

tutoraspects/patches/k8s-deployments

Some requests of superset in the dashboard UI were failing with the following caddy log:
`readfrom tcp 172.18.0.9:60208->172.18.0.8:8088: write tcp 172.18.0.9:60208->172.18.0.8:8088: use of closed network connection`
Keep in mind that this happening on HTTP 2 with Caddy which is the default tutor configuration. After further research/testing the solution was to increase `GUNICORN_KEEPALIVE` from 2 to 5, which is an environment variable that the default Superset deployment script supports: https://github.com/apache/superset/blob/26df7b4ad5c6c48bd1cc4a015c80cea56cb4d493/docker/run-server.sh#L30
After this change, all requests are successful to the Superset API.

fix: increase gunicorn keep alive to 5

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_watched_video_segments.yaml
tutoraspects/templates/openedx-assets/queries/fact_at_risk_watched_video_segments.sql
tutoraspects/templates/openedx-assets/queries/fact_video_watches.sql
tutoraspects/templates/openedx-assets/queries/fact_watched_video_segments.sql

This change moves `fact_watched_video_segments` back to being a virtual dataset. Unfortunately, the query had a more significant performance hit than expected when it was moved to dbt. By moving the query back into Superset and restoring our use of SQL templating, we can regain those performance benefits.

feat: use jinja for watched video segments query (FC-0051)

---

.github/workflows/bump-version.yaml
.github/workflows/pull-translations.yaml
.github/workflows/release.yaml
.github/workflows/test.yml
.github/workflows/upgrade-python-requirements.yml
catalog-info.yaml

We moved from "main" to "nightly" to better match Tutor standard release branch naming conventions.

chore: Update automation for new default branch

---

tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0002_raw_xapi_table.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0029_drop_json_column.py
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0030_rename_vector_json_column.py

The JSON column has been deprecated from ClickHouse. We briefly used it, but removed it some time ago and the old migrations break on some newer versions of ClickHouse, so this PR removes all references to that column.

Remove JSON column from migrations

---

.github/workflows/integration-test.yml
tutoraspects/commands_v0.py
tutoraspects/commands_v1.py

This PR adds a command to only run init tasks for ClickHouse.

feat: add init clickhouse job

---

tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py

This PR fixes an issue with the `can_view_courses` filter:
```bash
File "/app/pythonpath/superset_config_docker.py", line 107, in can_view_courses_wrapper
return memoized_func()(can_view_courses)(*args, **kwargs)
TypeError: memoized_func() missing 1 required positional argument: 'key'
```
The key format is now necessary by Superset 4.0.0 and was changed on this PR: https://github.com/apache/superset/pull/25900

fix: add key for memoized_func

---

tutoraspects/templates/openedx-assets/queries/fact_learner_summary.sql

Change SQL to user greater of enrolled at date or last visited - 'last visited' defaults to 1970/1/1 on creation.
Closes: https://github.com/openedx/platform-plugin-aspects/issues/55

fix: Use enrolled date if last visited is not set

---

tutoraspects/patches/openedx-dev-dockerfile-post-python-requirements
tutoraspects/patches/openedx-dockerfile-post-python-requirements

This includes a fix to allow backfill to work with the new ERB config format.
Full list of changes: https://github.com/openedx/event-routing-backends/compare/v9.0.1...v9.2.1

fix: Bump event-routing-backends to v9.2.1

---

.github/workflows/integration-test.yml

In most cases dev/local were skipping trying to actually do the dump due to the course already existing in Clickhouse. This should force the code path to be run that we were expecting.

build: Make CI force course_overviews dump

---

tutoraspects/asset_command_helpers.py
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Course_Information_fa249d.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Cumulative_Enrollments_by_Track_f207c8.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Cumulative_Interactions_c44e43.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Current_Enrollees_00de2f.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Distribution_of_Current_Course_Grade_ea5656.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Enrollees_per_Enrollment_Track_e58419.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Learners_with_Passing_Grade_b40cda.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Page_Engagement_Over_Time_d7bfef.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Partial_and_Full_Video_Views_2232c3.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Partial_and_Full_Video_Views_bfffb9.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Problem_Attempts_ba14d2.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Section_Summary_474171.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Subsection_Summary_2a8d96.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_c8c363.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_per_Section_Subsection_5d0329.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Watched_Video_Segments_2985a9.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Course_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_navigation_completion.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_student_status.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_video_plays.yaml

Includes various UI fixes, and renaming of charts for consistency.

Course dashboard updates from the Edunext sandbox

---

.github/workflows/integration-test.yml
tutoraspects/commands_v1.py
tutoraspects/templates/aspects/apps/superset/pythonpath/collect_dbt_lineage.py
tutoraspects/templates/aspects/build/aspects-superset/requirements.txt
tutoraspects/templates/base-docker-compose-services

We'll use this in aspects-dbt CI to keep the model to dashboard mappings up to date. Leaving this in draft for the moment so we can discuss the direction. The idea is to have this command to generate an exposures file that we can bring back to aspects-dbt.
This should allow us visibility into which datasets are actually being used (or not used) in Superset and let us remove unused models. However there's a dependency problem where tutor-contrib-aspects needs to update to use a new aspects-dbt and there may be error-causing issues generating the exposures until it is updated. I haven't given much thought to how to resolve that yet, but we could move the dbt docs to that repo instead and use the combined official tutor-contrib-aspects / aspects-dbt version to make the file / docs.

feat: Add command to generate a dbt exposures file

---

.github/workflows/bump-version.yaml
README.rst

This attempts to remove the ability to override the build version manually, which I don't think ever worked quite right. So we'll trust the automation going forward. Also adds a bit to the docs about how to release, since I always want to trigger the wrong workflow.

Force build version, add release instructions to docs

---

tutoraspects/asset_command_helpers.py
tutoraspects/commands_v1.py
tutoraspects/templates/aspects/apps/superset/pythonpath/create_assets.py

The custom Superset assets are all pushed into a single assets.yaml file, and need to be separated by `---` lines. This fixes the ability to read multiple custom assets from the assets.yaml / `superset-extra-assets` patch.
Also allows the `import_superset_zip` command to serialize assets to other locations so that extensions can use it as well.

fix: Import of custom Superset assets

---

.github/workflows/release.yaml

This will fix the warning of 'The master branch version has been sunset for gh-action-pypi-publisher'

fix: pypi-publish master branch sunset

---

README.rst

If this image is not built, the Superset database connections will have the wrong password and other settings changes will not be used.
Closes: #893

docs: Update readme to include the Superset image

---

README.rst

The `transform-tracking-logs` do command in the README was incorrectly spelled as `transform_tracking_logs`. I've updated this in the README.

docs: correct the transform-tracking-logs do command name

---

tutoraspects/patches/openedx-dev-dockerfile-post-python-requirements
tutoraspects/patches/openedx-dockerfile-post-python-requirements
tutoraspects/plugin.py
tutoraspects/templates/aspects/apps/aspects/dbt/profiles.yml
tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0039_event_sink_tag_taxonomy.py
tutoraspects/templates/aspects/apps/aspects/scripts/bootstrap.sh

This PR adds the tables needed for tags.
Depends on https://github.com/openedx/platform-plugin-aspects/pull/82

feat: add tag related tables

---

tutoraspects/patches/openedx-common-settings
tutoraspects/plugin.py
tutoraspects/templates/aspects/jobs/init/lms/init-lms.sh

This PR improves the init lms task time by using settings to enable the sinks instead of using waffle flags.
Make sure to drop all `event_sink_clickhouse_*_enabled` records on the waffle flag admin in the LMS:
- Search `event_sink_clickhouse` in the admin for the waffle flag model.
- Select all records.
- In the action menu, select the `Delete all records` action and proceed with the deletion.

perf: improve init lms task time by using settings instead of waffle flags

---

.github/workflows/build-image.yaml
tutoraspects/asset_command_helpers.py

This PR allows the formatting of SQL statements for the datasets.

fix(dev): sql parse dataset SQL statement

---

requirements/base.in
requirements/base.txt
requirements/dev.in
tutoraspects/patches/openedx-dev-dockerfile-post-python-requirements
tutoraspects/patches/openedx-dockerfile-post-python-requirements
tutoraspects/templates/aspects/apps/clickhouse/dev_config/server_config.xml
tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_jinja_filters.py
tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py

This PR adds a jinja filter called 'filtered_dashboard' which creates a link to a dashboard given the dashboard slug, the column name to filter, and the filter ID.

feat: add jinja filter to render a link to a dashboard

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Course_Info_ccdd7d.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Learner_Performance_b0e170.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Learner_Performance_b518f3.yaml

This PR fixes a couple of issues with the dashboards.

fix(assets): latest details of dashboard changes

---

tutoraspects/templates/openedx-assets/queries/fact_learner_summary.sql
tutoraspects/templates/openedx-assets/queries/learner_performance.sql

Performance improvements for learner summary
```
5. individual-learner - Learner Summary
Superset time: 2.011835 (s).
Query duration: 0.17 (s).
Result rows: 100
Memory Usage (MB): 30.506019592285156
Row count (superset) 100
Filters: [{'column': 'emission_time'}]
11. individual-learner - Learner Summary
Superset time: 0.915487 (s).
Query duration: 0.047 (s).
Result rows: 100
Memory Usage (MB): 12.710393905639648
Row count (superset) 100
Filters: [{'column': 'emission_time'}]
```
Performance improvements for Learner Performance:
```
0 rows in set. Elapsed: 2.204 sec. Processed 3.84 million rows, 440.55 MB (1.74 million rows/s., 199.91 MB/s.)
Peak memory usage: 758.23 MiB.
0 rows in set. Elapsed: 0.598 sec. Processed 3.84 million rows, 440.55 MB (6.42 million rows/s., 736.68 MB/s.)
Peak …
```

perf(sql): use last_course_visit mv for learner summary query

---

tutoraspects/commands_v1.py
tutoraspects/templates/aspects/apps/superset/pythonpath/performance_metrics.py

This PR brings improvements to the performance metrics script by ordering them by clickhouse query time, and adds the filter as if the charts were loaded from the Superset UI

feat(metrics): sort metrics by clickhouse query time

---

tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py

Allows Django staff users to see the course-level dashboards, currently they never get that permission.
Note: This behavior will give Django staff users access to all course data for all courses in Aspects.
Closes: https://github.com/openedx/openedx-aspects/issues/291

fix: add instructor role to operators too

---

tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_5b00f7.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/charts/Video_Engagement_6b7610.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/dashboards/Course_Comparison_Dashboard.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/course_information.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/tag_filter.yaml
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/watched_video_duration.yaml
tutoraspects/templates/openedx-assets/queries/tag_filter_dataset.sql

fixes for
https://github.com/openedx/openedx-aspects/issues/289
"One more with the course comparison dashboard, the tag filter is currently giving me an error message:" (https://axim-collaborative.slack.com/archives/C07GGRUQS5T/p1729176527571429)

fix: fix enrollment count, video count, tag filter

---

tutoraspects/patches/caddyfile

This fixes the DBT docs hosting by updating the service Caddy was pointing to

fix: point aspects docs to the right service

---

README.rst
requirements/dev.in
tutoraspects/filters.py
tutoraspects/plugin.py

This PR adds default autoscaling values for Ralph and Superset

feat: add autoscaling values for ralph and superset

---

tutoraspects/plugin.py
tutoraspects/templates/base-docker-compose-services

Adds `IMAGES_BUILD_MOUNTS` and  `COMPOSE_MOUNTS` support for development on Superset within Aspects.
Preliminary step to work on https://github.com/openedx/openedx-aspects/issues/299
1. Install this plugin's branch to your tutor virtualenv.
2. Clone the Superset repo to your local environment: `git clone https://github.com/apache/superset.git`
3. Add a mount for where you cloned superset, e.g. `tutor dev mounts add /dev/superset`
4. Check that the mount shows up in the list, e.g `tutor dev mounts list` should have:
```
- name: /dev/superset
build_mounts:
- image: aspects-superset
context: superset
compose_mounts:
- service: superset
container_path: /app
```
5. Rebuild your superset image: `tutor dev images build aspects-superset`
6. Stop `superset` and run a shell to check that your …

feat: add bind and compose mount settings for superset

---

tutoraspects/patches/local-docker-compose-dev-services
tutoraspects/patches/local-docker-compose-jobs-services
tutoraspects/patches/local-docker-compose-services

Aspects would fail if someone was using an external MySQL server
We now only add MySQL as a dependency to containers if RUN_MYSQL=True

fix: do not add mysql as a dependency when RUN_MYSQL=False

---

tutoraspects/patches/local-docker-compose-permissions-command
tutoraspects/patches/local-docker-compose-permissions-volumes

On the Sumac sandbox we've seen errors regarding the ability of ClickHouse to write to its bind mounted data directory. This hasn't seemed to have impacted usability, and hasn't appeared elsewhere that we have seen. This fix was suggested by Régis, and doesn't seem to break anything in local testing but we have no ability to reproduce the issue so it's speculative.
Original thread: https://github.com/overhangio/openedx-release-demo/pull/72#issuecomment-2515038220
Patches are here, for reference: 
- https://github.com/overhangio/tutor/blob/release/tutor/templates/apps/permissions/setowners.sh
- https://github.com/overhangio/tutor/blob/release/tutor/templates/local/docker-compose.yml#L22

fix: Set Clickhouse data dir permissions

---

README.rst

Reworked README for improved clarity

---

tutoraspects/templates/aspects/apps/superset/pythonpath/performance_metrics.py
tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/query_log.yaml

1. Add check to compare count of slices to rowcount from clickhouse to ensure data for all slices has been returned
2. Add 'strip' to remove whitespace that caused memory=none issues
3. Simplify ch query

fix: Performance testing script updates

---

.github/workflows/bump-version.yaml

A note on this - the current code for [github-tag-action](https://github.com/mathieudutour/github-tag-action) does not support conventionalcommit analyzer (only angular) so our commit messages are not interpreted correctly which means using the 'bump version' action in GitHub only bumps minor releases, not major.
There is a [PR](https://github.com/mathieudutour/github-tag-action/pull/227) that will change this, but it needs to be merged/compiled into the [workplace action](https://github.com/marketplace/actions/github-tag) before we can use it.
So for now, we will force the action to do a major version bump, and hope that the PR gets reviewed soon so we can remove this line and instead specify `commit_analyzer_preset: conventionalcommit`

fix: force major version bump

---

tutoraspects/patches/local-docker-compose-services

The clickhouse and ralph containers should restart automatically similar to the [superset containers](https://github.com/openedx/tutor-contrib-aspects/blob/1da0fcfcd245223e5e95ca1f0df68251cff8c819/tutoraspects/templates/base-docker-compose-services#L13).
This is a recurring issue we have faced where the clickhouse and ralph containers would just randomly stop and we would only find out after debugging why we are missing some data.
Unfortunately, we didn't find the logs to find out why the containers stopped or crashed. If we ever do, I'll make sure to edit this PR description and add them here.

fix: restart clickhouse and ralph automatically

---

tutoraspects/plugin.py
tutoraspects/templates/openedx-assets/queries/graded_subsection_performance.sql
tutoraspects/templates/openedx-assets/queries/graded_subsection_results.sql
tutoraspects/templates/openedx-assets/queries/problem_responses.sql
tutoraspects/templates/openedx-assets/queries/problem_results.sql
tutoraspects/templates/openedx-assets/queries/watched_video_segments.sql

The In-Context front end only passes the last hash string of the block id to the dashboards for filtering
block-v1:course-v1:Org0+DemoX+2bc51b+type@problem+block@**42e10810**

fix: use end of block id for in-context filtering

---

tutoraspects/plugin.py

Authoring MFE's slots were updated to use the namespaced ID format for all the slots in frontend-app-authoring PR#1854.
This commit brings the latest IDs to the Authoring MFE patch and also upgrades the unit-page sidebar slot to the latest version - v2.

chore: upgrade Authoring MFE slot IDs to namespaced version

---

tutoraspects/patches/mfe-dockerfile-post-npm-install-authoring

The changes remove legacy-peer-dependency flag because we matched the dependency in frontend-plugin-aspects, this helps to be flexible with installing dependencies as reported in #1091.
**Discussions**: 
https://github.com/openedx/frontend-plugin-aspects/pull/51
**Dependencies**: None
**Screenshots**: Always include screenshots if there is any change to the UI.
**Testing instructions**:
Same as https://github.com/openedx/frontend-plugin-aspects/pull/51

fix: Removes legacy peer dependency flag to make the install flexible

---

requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/translations.txt

This package doesn't seem to be used, has not been updated in years, and has a downstream dependency with a security vulnerability (future) that is generating warnings.

chore: Remove unused transifex-python dependency

---

requirements/base.in
requirements/base.txt
requirements/translations.in
requirements/translations.txt

Click 8.3 doesn't work with the latest version of tutor. Once we start testing for Ulmo, this will cause failures

fix: Pin earlier version of Click until bug is fixed
